delete from users;
delete from films;
delete from  likes;
delete from  friends;

CREATE TABLE IF NOT EXISTS users
(
    "id"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"     varchar(40)        NOT NULL,
    "login"    varchar(30) UNIQUE NOT NULL,
    "email"    varchar(30)        NOT NULL,
    "birthday" timestamp
);

CREATE TABLE IF NOT EXISTS films
(
    "id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        varchar(30) NOT NULL,
    "description" varchar(100),
    "releaseDate" timestamp,
    "genre"       varchar(10) NOT NULL,
    "mpa"         varchar(10) NOT NULL,
    "duration"    integer     NOT NULL
);

CREATE TABLE IF NOT EXISTS likes
(
    "id"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "film_id" integer NOT NULL,
    "user_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS friends
(
    "id"                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"           integer NOT NULL,
    "friends_id"        integer NOT NULL,
    "confirmation"      boolean NOT NULL,
    "confirmation_date" timestamp
);